services:
  network-scanner:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HTTP_PORT=9998
    volumes:
      - ".:/var/www/html"
    network_mode: host
